version: '3.8'

services:
  api:
    container_name: gb-ui-api

    build:
      context: .
      dockerfile: docker/app/Dockerfile

    restart: unless-stopped

    env_file:
      - .env

    ports:
      - ${EXTERNAL_PORT}:8000



